src/Entity/Cart.php
<?php

namespace App\Entity;

class Cart
{
    /**
     * @var CartItem[]
     */
    private $items = [];

    /**
     * @return CartItem[]|array
     */
    public function getItems(): array
    {
        return $this->items;
    }

    public function addItem(CartItem $cartItem): CartItem
    {
        foreach ($this->items as $item) {
            if ($cartItem->matches($item)) {
                $item->increaseQuantity($cartItem->getQuantity());

                return $item;
            }
        }

        $this->items[] = $cartItem;

        return $cartItem;
    }

    public function removeItem(CartItem $cartItem)
    {
        foreach ($this->items as $key => $item) {
            if ($cartItem->matches($item)) {
                unset($this->items[$key]);
                $this->items = array_values($this->items);

                return;
            }
        }
    }

    public function getTotal(): int
    {
        return array_reduce($this->getItems(), function($accumulator, CartItem $item) {
            return $accumulator + $item->getTotal();
        }, 0);
    }

    public function getTotalString(): string
    {
        return (string) ($this->getTotal() / 100);
    }

    public function countTotalItems(): int
    {
        return array_reduce($this->getItems(), function($accumulator, CartItem $item) {
            return $accumulator + $item->getQuantity();
        }, 0);
    }

    public function findItem(Product $product, ?Color $color): ?CartItem
    {
        foreach ($this->items as $item) {
            if ($item->getProduct() === $product && $item->getColor() === $color) {
                return $item;
            }
        }

        return null;
    }

    public function hasItem(CartItem $cartItem)
    {
        return (bool) $this->findItem($cartItem->getProduct(), $cartItem->getColor());
    }
}

src/Entity/Color.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ColorRepository")
 */
class Color
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $hexColor;

    public function __construct(string $name, string $hexColor)
    {
        $this->name = $name;
        $this->hexColor = $hexColor;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHexColor(): ?string
    {
        return $this->hexColor;
    }

    public function setHexColor(string $hexColor): self
    {
        $this->hexColor = $hexColor;

        return $this;
    }

    public function getRed(): string
    {
        return hexdec(substr($this->hexColor, 0, 2));
    }

    public function getGreen(): string
    {
        return hexdec(substr($this->hexColor, 2, 2));
    }

    public function getBlue(): string
    {
        return hexdec(substr($this->hexColor, 4, 2));
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("product:read")
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("product:read")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank
     */
    private $brand = 'Low End Luxury';

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     * @Assert\GreaterThan(0)
     * @Assert\NotBlank()
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     */
    private $stockQuantity = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Color")
     */
    private $colors;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $imageFilename = 'floppy-disc.png';

    public function __construct()
    {
        $this->colors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getPriceString(): string
    {
        return (string) $this->price / 100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStockQuantity(): ?int
    {
        return $this->stockQuantity;
    }

    public function setStockQuantity(int $stockQuantity): self
    {
        $this->stockQuantity = $stockQuantity;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): self
    {
        if (!$this->colors->contains($color)) {
            $this->colors[] = $color;
        }

        return $this;
    }

    public function removeColor(Color $color): self
    {
        if ($this->colors->contains($color)) {
            $this->colors->removeElement($color);
        }

        return $this;
    }

    public function hasColors(): bool
    {
        return count($this->colors) > 0;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    /**
     * @Groups("product:read")
     */
    public function getImageUrl(): string
    {
        return sprintf('/uploads/products/'.$this->imageFilename);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Color;
use App\Entity\Product;
use App\Form\AddItemToCartFormType;
use App\Repository\CategoryRepository;
use App\Repository\ColorRepository;
use App\Repository\ProductRepository;
use App\Service\CartStorage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

final class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="app_cart")
     */
    public function shoppingCart(CartStorage $cartStorage, ProductRepository $productRepository): Response
    {
        $featuredProduct = $productRepository->findFeatured();
        $addToCartForm = $this->createForm(
            AddItemToCartFormType::class,
            null,
            [
                'product' => $featuredProduct,
            ]
        );

        return $this->render(
            'cart/cart.html.twig',
            [
                'cart' => $cartStorage->getOrCreateCart(),
                'featuredProduct' => $featuredProduct,
                'addToCartForm' => $addToCartForm->createView(),
            ]
        );
    }

    /**
     * @Route("/cart/_list", name="_app_cart_list")
     */
    public function _shoppingCartList(CartStorage $cartStorage): Response
    {
        return $this->render(
            'cart/_cartList.html.twig',
            [
                'cart' => $cartStorage->getOrCreateCart(),
            ]
        );
    }

    /**
     * @Route("/product/{id}", name="app_cart_add_item", methods={"POST"})
     */
    public function addItemToCart(
        Product $product,
        Request $request,
        CategoryRepository $categoryRepository,
        CartStorage $cartStorage
    ) {
        $addToCartForm = $this->createForm(
            AddItemToCartFormType::class,
            null,
            [
                'product' => $product,
            ]
        );

        $addToCartForm->handleRequest($request);
        if ($addToCartForm->isSubmitted() && $addToCartForm->isValid()) {
            $cart = $cartStorage->getOrCreateCart();
            $cart->addItem($addToCartForm->getData());
            $cartStorage->save($cart);

            $this->addFlash('success', 'Item added!');

            return $this->redirectToRoute(
                'app_product',
                [
                    'id' => $product->getId(),
                ]
            );
        }

        return $this->render(
            'product/show.html.twig',
            [
                'product' => $product,
                'categories' => $categoryRepository->findAll(),
                'addToCartForm' => $addToCartForm->createView(),
            ]
        );
    }

    /**
     * @Route("/cart/remove/{productId}/{colorId?}", name="app_cart_remove_item", methods={"POST"})
     */
    public function removeItemToCart(
        $productId,
        $colorId,
        Request $request,
        CartStorage $cartStorage,
        ProductRepository $productRepository,
        ColorRepository $colorRepository
    ) {
        /** @var Product|null $product */
        $product = $productRepository->find($productId);
        /** @var Color|null $color */
        $color = $colorId ? $colorRepository->find($colorId) : null;

        if (!$product) {
            $this->createNotFoundException();
        }

        if (!$this->isCsrfTokenValid('remove_item', $request->request->get('_token'))) {
            throw new BadRequestHttpException('Invalid CSRF token');
        }

        $cart = $cartStorage->getOrCreateCart();
        $cartItem = $cart->findItem($product, $color);
        if ($cartItem) {
            $cart->removeItem($cartItem);
        }
        $cartStorage->save($cart);

        $this->addFlash('success', 'Item removed!');

        return $this->redirectToRoute('app_cart');
    }
}

templates/cart/_cartList.html.twig
<div>
    <div class="row p-3">
        <div class="col-3">
            Item Name
        </div>
        <div class="col-3">
            Quantity
        </div>
        <div class="col-3">
            Price
        </div>
        <div class="col-3"></div>
    </div>
    {% for item in cart.items %}
        <div class="cart-item row p-3"
             data-action="submit-confirm:async:submitted->reload-content#refreshContent">
            <div class="col-2">
                {{ item.product.name }}
            </div>
            <div class="col-1">
                {% if item.color %}
                    <span class="color-square"
                          style="background-color: rgb({{ item.color.red }}, {{ item.color.green }}, {{ item.color.blue }});"></span>
                {% endif %}
            </div>
            <div class="col-3">
                {{ item.quantity }}
            </div>
            <div class="col-3">
                {{ item.totalString|format_currency('USD') }}
            </div>
            <div class="col-3">
                <form method="post"
                      action="{{ path('app_cart_remove_item', {
                          productId: item.product.id,
                          colorId: item.color ? item.color.id: null,
                      }) }}"
                        {{ stimulus_controller('submit-confirm',{
                            confirmButtonText: 'Yes, remote it',
                            icon: 'warning',
                            submitAsync: true,
                            title: 'Remove this item?'
                        }) }}
                      data-action="submit-confirm#onSubmit">
                    <input type="hidden" name="_token" value="{{ csrf_token('remove_item') }}"/>
                    <button class="btn btn-info btn-sm">
                        Remove
                    </button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="col-12">
            Your cart is empty! Get to shopping!
        </div>
    {% endfor %}

    {% if cart.items|length > 0 %}
        <div class="p-3">
            Total: <strong>{{ cart.totalString|format_currency('USD') }}</strong>
        </div>
    {% endif %}
</div>

{% if cart.items|length > 0 %}
    <div>
        <a href="{{ path('app_checkout') }}" class="btn btn-primary">
            Check Out &gt;&gt;
        </a>
    </div>
{% endif %}

templates/cart/_featuredSidebar.html.twig
<div class="component-light product-show p-3 mb-5">
    <h5 class="text-center">Featured Product!</h5>
    <a href="{{ path('app_product', { id: featuredProduct.id }) }}">
        <img
            alt="{{ featuredProduct.name }}"
            src="{{ asset('/uploads/products/'~featuredProduct.imageFilename) }}"
            class="d-block"
        >
    </a>
    <div class="pt-3">
        <h6>
            {{ featuredProduct.name }}

            {{ featuredProduct.priceString|format_currency('USD') }}
        </h6>

        {{ include('product/_cart_add_controls.html.twig') }}
    </div>
</div>

templates/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid mt-4">
        <div class="row">
            <aside class="col-xs-12 col-lg-3">
                {% if featuredProduct %}
                    {{ include('cart/_featuredSidebar.html.twig') }}
                {% endif %}
            </aside>
            <div class="col-xs-12 col-lg-9 cart">
                <h1>Shopping Cart</h1>
                <div class="component-light p-3"
                        {{ stimulus_controller('reload-content',{
                            url: path('_app_cart_list')
                        }) }}>
                    {{ include('cart/_cartList.html.twig') }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}